version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: crm_database
      POSTGRES_USER: crm_user
      POSTGRES_PASSWORD: crm_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/database:/docker-entrypoint-initdb.d
    restart: unless-stopped

volumes:
  postgres_data: